steps:
  - id: "init"
    name: hashicorp/terraform:1.12.2
    entrypoint: sh
    args:
      - "-c"
      - terraform init -no-color -upgrade
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - id: "check_format"
    name: hashicorp/terraform:1.12.2
    entrypoint: sh
    args:
      - "-c"
      - terraform fmt -recursive
    volumes:
      - name: "ssh"
        path: /root/.ssh
timeout: 600s
logsBucket: gs://sp-archived-drive
