substitutions:
  _DRIFT_DETECT: "false"
steps:
  - id: "init"
    name: hashicorp/terraform:1.12.2
    entrypoint: sh
    args:
      - "-c"
      - terraform init -no-color -upgrade
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - id: "check_format"
    name: hashicorp/terraform:1.12.2
    entrypoint: sh
    args:
      - "-c"
      - terraform fmt -recursive
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - id: "plan"
    name: hashicorp/terraform:1.12.2
    entrypoint: sh
    args:
      - -c
      - |
          if [[ "$_DRIFT_DETECT" == "true" ]]; then
            echo "Running drift detection"    
            terraform plan -no-color --detailed-exitcode
          else
            terraform plan -no-color
          fi
    volumes:
      - name: "ssh"
        path: /root/.ssh
